pub mod adapter_trait;
pub mod background_adapter;
pub mod desktop_adapter;
pub mod kernel_a_adapter;
pub mod kernel_b_adapter;
pub mod orbit_adapter;
pub mod vgm_adapter;
pub mod vrm_adapter;
pub mod vum_adapter;
