# Samaris Build Config — Full ISO
BUILD_CONFIG_ARCH_X86_64=1
BUILD_CONFIG_ARCH_AARCH64=1
BUILD_CONFIG_AI_LLM=1
BUILD_CONFIG_AI_STT=1
BUILD_CONFIG_AI_TTS=1
BUILD_CONFIG_AI_POSTINSTALL=0
BUILD_CONFIG_VOLT_BENCH=0
BUILD_CONFIG_SVC_NETWORK=1
BUILD_CONFIG_SVC_CUPS=1
BUILD_CONFIG_SVC_POWER=1
BUILD_CONFIG_DESKTOP_UI=1
BUILD_CONFIG_DESKTOP_BROWSER=1
BUILD_CONFIG_DESKTOP_DEMO=1
BUILD_CONFIG_MODE=full
BUILD_CONFIG_USE_DOCKER=1
BUILD_CONFIG_FORCE=0
BUILD_CONFIG_DRY_RUN=0
